FROM nvidia/cudagl:10.0-devel-ubuntu18.04
RUN apt-get update &&
RUN set -ex; if
RUN apt-get update &&
RUN set -ex; apt-get
ENV PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV LANG=C.UTF-8
RUN apt-get update &&
ENV GPG_KEY=97FC712E4C024BBEA48A61ED3A5CA953F73C700D
ENV PYTHON_VERSION=3.4.10
RUN set -ex &&
RUN cd /usr/local/bin &&
ENV PYTHON_PIP_VERSION=19.0.3
